
 
services: -docker 

script:
# Build
- docker build -t udagram-api-feed ./udagram-api-feedv:9
- docker build -t udagram-api-user ./udagram-api-userv:9
- docker build -t udagram-frontend ./udagram-frontend:v9
- docker build -t reverseproxy ./udagram-reverseproxy:v9
# Tagging
- docker tag udagram-api-feed sherif102/udagram-api-feed:v9
- docker tag udagram-api-user sherif102/udagram-api-user:v9
- docker tag udagram-frontend sherif102/udagram-frontend:v9
- docker tag reverseproxy sherif102/reverseproxy:v9
#push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push sherif102/udagram-frontend:v9
- docker push sherif102/udagram-api-user:v9
- docker push sherif102/reverseproxy:v9
- docker push sherif102/udagram-api-feed:v9