apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  credentials: W3NoZXJpZl0KYXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBWENGQk5ZU0s0UkhWN0VHSwphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSB1cUdPK0JlbVNZMkV2ZEtETDVnSUk3VTJaTktuUEdGMXp3WENLcEdECgoK